apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentx-deployment
  namespace: studentx
spec:
  selector:
    matchLabels:
      app: studentx
  template:
    metadata:
      labels:
        app: studentx
    spec:
      containers:
      - name: studentx
        image: nginx
